/* ============================================================================
   QUESTION BANK — ENGLISH
   Aligned to the PMP Exam Content Outline 2026 (effective 9 July 2026)
   and the PMBOK Guide 8th edition (6 principles, 7 performance domains,
   5 focus areas with 40 processes).
   Weights: People 33% · Process 41% · Business Environment 26%
   These are independent items, not translations of the Spanish bank.
   ============================================================================ */
const QUESTIONS_EN = [

/* ==========================  PEOPLE (33%)  ========================== */

{id:'en-p01', domain:'people', topic:'Conflict management',
 q:'Two team leads have escalated the same disagreement about test coverage standards to you three times in two weeks. Each time you have made a ruling and each time the dispute resurfaces in a slightly different form. What is the most effective action?',
 o:['Make a final binding ruling and instruct both leads that the matter is closed',
    'Bring both leads together to agree a written standard and the decision rule they will use for future disputes of this type',
    'Separate their areas of responsibility so that neither depends on the other',
    'Escalate the disagreement to the sponsor for a definitive decision'],
 a:1,
 r:['Correct on the surface, wrong in substance. You have already ruled three times and the dispute keeps returning, which is direct evidence that rulings do not resolve it. Issuing a fourth, more forceful ruling repeats a demonstrably failed approach.',
    'Correct. The recurrence pattern is the diagnostic clue: the underlying problem is not the individual disputes but the absence of an agreed standard and an agreed way to settle such questions. Facilitating the leads to build both jointly resolves the class of conflict rather than one instance, and gives them ownership of the outcome.',
    'Separating responsibilities removes the friction by removing the collaboration, which is a heavy structural cost to avoid a solvable disagreement. It also tends to create silos and inconsistent standards across the product.',
    'Escalating a recurring technical-standards dispute to the sponsor is disproportionate and signals that the project cannot govern itself. The sponsor also lacks the technical context to set a durable standard.'],
 ref:'2026 ECO People · manage conflict; PMBOK 8 — Team performance domain'},

{id:'en-p02', domain:'people', topic:'Servant leadership',
 q:'During a retrospective the team says they cannot estimate reliably because requirements arrive incomplete from the business analyst, who reports to a different manager. The team has raised this twice before. What should the project manager do?',
 o:['Coach the team to estimate with wider ranges to reflect the uncertainty',
    'Work with the analyst and their manager to agree an entry standard for requirements, and follow up until it holds',
    'Ask the team to write the missing requirements themselves during refinement',
    'Accept the constraint and add a contingency buffer to each sprint'],
 a:1,
 r:['Wider ranges make the estimates more honest but do nothing about the cause. The team has raised this three times now; responding with an estimation technique tells them the impediment itself will not be addressed.',
    'Correct. This is a cross-boundary impediment the team cannot fix on its own, and removing it is a core servant-leadership responsibility. The durable fix is an agreed definition of ready or entry standard negotiated with the analyst and their manager, plus follow-up, since a one-off conversation rarely changes a recurring pattern.',
    'Having the team write the missing requirements shifts work onto them without authority or business context, and quietly absolves the analyst. It converts a process gap into unpaid extra effort for the team.',
    'Buffering each sprint absorbs the symptom permanently and prices the dysfunction into the plan. It also hides the problem from the organisation, which removes any pressure to fix it.'],
 ref:'2026 ECO People · remove impediments; Agile Practice Guide'},

{id:'en-p03', domain:'people', topic:'Stakeholder engagement',
 q:'A regulatory affairs director has high authority over your product launch but has shown little interest so far, declining most invitations. Using a power/interest analysis, what is the appropriate engagement strategy?',
 o:['Manage closely with frequent detailed updates and standing meeting invitations',
    'Keep satisfied: provide concise, targeted information at the decision points that matter to her, without overwhelming her',
    'Monitor with minimal effort until she expresses interest',
    'Escalate to her manager to secure her formal participation'],
 a:1,
 r:['Manage closely is the strategy for stakeholders who are high on both power and interest. Applying it here floods a low-interest stakeholder with detail she has already signalled she does not want, which typically reduces engagement further.',
    'Correct. High power combined with low interest calls for keeping the stakeholder satisfied: give her enough targeted information to retain her support and surface issues that need her authority, concentrated at genuine decision points. This respects her limited attention while protecting the project from a late objection she could enforce.',
    'Minimal monitoring is the strategy for low power and low interest. Applying it to someone with high authority over the launch leaves the project exposed to a very late and very expensive intervention.',
    'Going to her manager to compel attendance damages the relationship and produces presence without engagement. It also skips the far cheaper step of tailoring communication to what she actually needs.'],
 ref:'2026 ECO People · engage stakeholders; PMBOK 8 — Stakeholder domain'},

{id:'en-p04', domain:'people', topic:'Team development',
 q:'A newly formed team is highly motivated but has never worked with the technology stack selected for the project. Which leadership style best fits this situation?',
 o:['Delegating: give the team full autonomy to determine how to proceed',
    'Directing: provide clear instructions, specific structure and close support while competence is built',
    'Supporting: offer encouragement without providing technical direction',
    'Laissez-faire: step back entirely so the team can learn through experimentation'],
 a:1,
 r:['Delegating suits teams with high competence and high commitment. This team has the commitment but not the competence, and delegating now sets them up to fail on decisions they lack the experience to make.',
    'Correct. Situational leadership matches style to readiness. High enthusiasm combined with low competence in the specific domain calls for a directing style: clear instructions, structure and close support, moving progressively to coaching, supporting and finally delegating as capability develops.',
    'Supporting assumes the team already has the competence and needs mainly encouragement or confidence. Here the gap is technical capability, which encouragement alone will not close.',
    'Laissez-faire is not a deliberate developmental style; it is the absence of leadership. With an inexperienced team it produces costly rework and erodes the motivation the team currently has.'],
 ref:'2026 ECO People · lead the team; situational leadership'},

{id:'en-p05', domain:'people', topic:'Psychological safety',
 q:'A junior tester discovered a serious defect two weeks ago but did not report it, later explaining they "did not want to be the person who delayed the release". What should the project manager address first?',
 o:['The tester\'s individual judgement, through a formal performance conversation',
    'The team environment that made silence feel safer than speaking up, and the norms that reward early disclosure',
    'The test process, by adding a mandatory defect-reporting checklist',
    'The release schedule, by adding time so future defects can be absorbed'],
 a:1,
 r:['Treating this as an individual performance failure guarantees that the next person to find a defect will be even less likely to report it. It punishes the disclosure and confirms exactly the fear that caused the silence.',
    'Correct. The tester\'s explanation identifies the cause precisely: they anticipated blame for delivering bad news. That is a psychological safety problem, and it is systemic rather than individual. Addressing the norms — making early disclosure explicitly welcome and visibly rewarded — is what changes behaviour across the whole team.',
    'A checklist enforces a mechanical step but does not touch the motivation for concealment. Someone who fears the consequences of reporting will find the checklist just as easy to leave incomplete.',
    'More schedule slack may reduce the pressure slightly, but it does not address the belief that the messenger will be blamed. A team that fears disclosure will conceal defects regardless of how much float exists.'],
 ref:'2026 ECO People · create a safe collaborative environment'},

{id:'en-p06', domain:'people', topic:'Virtual and hybrid teams',
 q:'Since moving to a hybrid model, decisions made informally by co-located members are repeatedly surprising remote colleagues, who then rework their tasks. What is the most effective intervention?',
 o:['Require all team members to be on site for the days when decisions are made',
    'Update the team working agreement so that every decision is recorded in the shared channel regardless of where it originates',
    'Appoint one co-located member to relay decisions to the remote members',
    'Reduce the number of decisions the team is permitted to make without the project manager'],
 a:1,
 r:['Mandating on-site presence treats location as the problem and imposes the cost on the people already disadvantaged. It also contradicts the hybrid model the organisation has adopted, and does nothing about undocumented decisions made on site.',
    'Correct. The failure is that decisions are not being captured, not that people are distributed. A team-owned working agreement requiring every decision to be recorded in the shared channel removes the information asymmetry at its source, and agreements the team sets itself are far more likely to be followed than rules imposed on it.',
    'A single relay point creates a bottleneck and a single point of failure, and information still arrives late and filtered. It also makes a team norm into one person\'s chore.',
    'Centralising decisions in the project manager slows everything down and removes the team autonomy that makes the team effective. It solves the visibility problem by eliminating the decisions themselves.'],
 ref:'2026 ECO People · collaborate with virtual teams'},

{id:'en-p07', domain:'people', topic:'Negotiation',
 q:'A key supplier opens contract renewal talks by stating their rate will rise 35% and that the figure is non-negotiable. You have two qualified alternative suppliers already assessed. What is the best approach?',
 o:['Accept the increase, since the supplier knows your systems and switching carries risk',
    'Explore the interests behind the figure — volume, contract length, payment terms — while testing it against your assessed alternatives',
    'Immediately terminate discussions and award to the cheapest alternative supplier',
    'Counter at half the increase to reach a quick settlement'],
 a:1,
 r:['Accepting a stated anchor without testing it rewards the tactic and forfeits the leverage you hold. Switching risk is real and worth pricing, but it is an input to the negotiation, not a reason to skip negotiating.',
    'Correct. You have a strong BATNA in the form of two assessed alternatives, which is precisely what gives you room to negotiate. Interest-based negotiation probes what sits behind the number — rates are frequently flexible on volume, term or payment timing — while the alternatives keep the pressure real and give you a genuine walk-away point.',
    'Awarding purely on price ignores weighted selection criteria such as technical capability, references and financial stability, and discards the incumbent\'s system knowledge without valuing it. It also abandons leverage you have not yet used.',
    'Splitting the difference concedes that the opening anchor was legitimate and gives away half of a number that may have been inflated entirely. It is positional bargaining, not interest-based negotiation.'],
 ref:'2026 ECO People · negotiate agreements'},

{id:'en-p08', domain:'people', topic:'Team performance',
 q:'A high performing developer has become withdrawn and missed two commitments. A colleague privately mentions the developer is dealing with a family illness. What should the project manager do?',
 o:['Reassign the developer\'s critical tasks immediately without raising the subject, to reduce their burden discreetly',
    'Speak with the developer privately, acknowledge that something appears difficult, and agree together what support or adjustment would help',
    'Raise the family situation in the next team meeting so the team can rally around them',
    'Take no action, since the information came from a third party and is personal'],
 a:1,
 r:['Silently removing their work makes a decision about someone without them and can feel like a demotion at their most vulnerable moment. Even well intended, it denies them agency over their own situation.',
    'Correct. A private, respectful conversation led by the person concerned lets them decide what to disclose and what support they want. It preserves dignity, gives you the information needed to make a proportionate adjustment, and is the appropriate use of second-hand information — as a prompt to check in, not as an established fact to act on.',
    'Disclosing someone\'s family health situation to the team without consent is a serious breach of privacy, regardless of the supportive intent. That disclosure is theirs to make.',
    'Complete inaction ignores visible performance changes in a valued colleague who may need support. The information should not be acted on as fact, but it is a legitimate reason to open a caring conversation.'],
 ref:'2026 ECO People · support team performance'},

{id:'en-p09', domain:'people', topic:'Knowledge transfer',
 q:'Your project is ending and the operations team will take over the product. Which approach transfers understanding most effectively?',
 o:['Deliver comprehensive written documentation and a formal handover presentation',
    'Combine documentation with a period of shadowing and joint incident handling, capturing the reasoning behind key design decisions',
    'Schedule a recorded three-hour walkthrough of the full system architecture',
    'Provide operations with access to the code repository and the issue history'],
 a:1,
 r:['Documentation and a presentation transfer explicit knowledge well, but the operational understanding that matters most — failure modes, why alternatives were rejected, where the fragile areas are — is tacit and rarely survives the translation to a document.',
    'Correct. Effective transfer pairs explicit artefacts with tacit transfer through joint work. Shadowing and handling real incidents together forces the reasoning to surface in context, and recording the rationale behind key decisions preserves the part that documentation alone consistently loses.',
    'A single long recorded session produces very low retention and gives no opportunity to apply the knowledge. It captures content while missing the interaction that makes the content usable.',
    'Repository and ticket access provides raw material but no interpretation. Operations would have to reverse-engineer intent from artefacts, which is slow, error-prone and wastes the outgoing team\'s availability.'],
 ref:'2026 ECO People · knowledge transfer; PMBOK 8'},

{id:'en-p10', domain:'people', topic:'Emotional intelligence',
 q:'In a steering meeting a senior executive publicly criticises your team\'s quality in strong personal terms. You feel a surge of anger. What is the most professional response?',
 o:['Respond firmly in the moment with equal force to defend your team publicly',
    'Acknowledge the concern, redirect to the specific evidence, and propose a focused session to work through the details',
    'Say nothing and raise the executive\'s behaviour with the sponsor afterwards',
    'Agree with the criticism in the moment to defuse the tension and correct the record later'],
 a:1,
 r:['Matching the force escalates a public confrontation and shifts the discussion from quality evidence to a personal contest. It is the impulsive reaction that self-regulation exists to interrupt, and it rarely improves how the team is perceived.',
    'Correct. This combines self-regulation, empathy for the concern underneath the delivery, and social skill in redirecting to evidence and to a forum where detail can actually be examined. It defends the team substantively without either capitulating or escalating.',
    'Silence in the moment leaves a public criticism unanswered in front of the people who heard it, which the team will read as a lack of support. Raising it later is reasonable, but it is not a substitute for handling the moment.',
    'Agreeing without checking the evidence publicly validates a possibly unfair characterisation of your team\'s work. Correcting it later is far harder than declining to concede it in the first place.'],
 ref:'2026 ECO People · emotional intelligence'},

{id:'en-p11', domain:'people', topic:'Decision making',
 q:'Your team must select between two integration approaches today. After discussion, four members favour option A, two favour option B, and both B supporters state they can fully support A if it is chosen. What is the appropriate way to close the decision?',
 o:['Continue discussion until all six genuinely prefer the same option',
    'Confirm consensus on option A by explicitly checking that the B supporters can commit, then decide',
    'Take a majority vote and record the four-to-two result',
    'Have the project manager decide unilaterally to save time'],
 a:1,
 r:['Consensus does not require unanimous preference, and insisting on it gives any individual an effective veto. With a decision due today, waiting for unanimity means not deciding at all.',
    'Correct. Consensus means everyone can support and commit to the decision, not that everyone prefers it. The B supporters have already indicated they can commit; making that explicit closes the decision with genuine buy-in and no unresolved dissent carried into implementation.',
    'A bare majority vote is faster but formally defeats two members without confirming their commitment, which typically shows up as weak follow-through. Here it is also unnecessary, since the commitment already exists and only needs to be surfaced.',
    'Deciding unilaterally discards the team\'s technical analysis and signals that the discussion was decorative. Autocratic decisions are appropriate in emergencies; this decision is already effectively made.'],
 ref:'2026 ECO People · collaborative decision making'},

{id:'en-p12', domain:'people', topic:'Self-organising teams',
 q:'A project manager new to agile begins assigning individual sprint backlog items to named developers each morning. Over two sprints, throughput falls and team members stop raising blockers early. What is the most likely cause?',
 o:['The team lacks the discipline to work without individual assignment',
    'Individual assignment prevents the team from self-organising, removes in-sprint rebalancing and dilutes collective ownership of the sprint goal',
    'The team is deliberately resisting the new project manager',
    'Throughput is a poor metric and the decline is probably measurement noise'],
 a:1,
 r:['Nothing indicates a discipline problem. The decline began with the change in practice, and inventing a team deficiency to explain it inverts the actual sequence of cause and effect.',
    'Correct. In Scrum the developers self-manage the sprint backlog, which is what allows work to be rebalanced when someone is blocked. External assignment creates individual silos, removes that flexibility, and weakens shared ownership of the sprint goal — which also explains why blockers stopped being raised, since they now look like individual failures.',
    'Attributing deliberate sabotage is an extraordinary claim with no supporting evidence, and it diverts attention from a clear structural cause that can actually be corrected.',
    'Throughput has limits as a metric, particularly across teams, but a sustained decline within one team across two sprints coinciding exactly with a practice change is a signal, not noise.'],
 ref:'2026 ECO People · empower the team; Agile Practice Guide'},

{id:'en-p13', domain:'people', topic:'Inclusion',
 q:'In refinement sessions, two team members contribute most of the discussion while three others rarely speak, although those three raise valuable points in one-to-one conversations. What should the facilitator do?',
 o:['Ask the two dominant members to speak less in sessions',
    'Change the format so contribution does not depend on competing for airtime: round-robin input, written pre-reads or silent estimation',
    'Accept the pattern, since those who speak most usually understand the topic best',
    'Collect the quieter members\' input privately and present it to the group'],
 a:1,
 r:['Asking someone to speak less addresses part of the imbalance but leaves the mechanism producing it untouched, and often creates awkwardness without drawing anyone else in.',
    'Correct. When contribution depends on competing for airtime, it systematically favours particular communication styles rather than the best thinking. Redesigning the mechanism — round-robin, written input before the session, silent estimation such as planning poker — brings every voice into the process by design.',
    'The scenario contradicts this directly: the quieter members contribute valuable points when the channel allows it. Equating volume of speech with quality of judgement is exactly the bias to correct.',
    'Acting as a permanent intermediary captures the input but keeps three people outside the actual discussion and makes them dependent on the facilitator. It patches the symptom without changing the dynamic.'],
 ref:'2026 ECO People · foster inclusion and diversity'},

{id:'en-p14', domain:'people', topic:'Team formation',
 q:'Seven weeks in, a team is openly disputing who decides technical priorities and one member questions your authority in front of the group. Another suggests reorganising the team because "this is not working". How should you interpret this?',
 o:['The team is in the storming stage, a normal and necessary phase to be facilitated rather than avoided',
    'The team has reached performing, and the vigorous debate reflects maturity',
    'Team formation has failed and the group should be reconstituted with different people',
    'The team is in norming, and the disagreement shows the norms are already settled'],
 a:0,
 r:['Correct. Disputes over roles, contested decision rights and challenges to the leader\'s authority are the defining features of storming, and appearing around week seven is entirely expected. The role of the project manager is to facilitate the phase — clarifying roles and decision rules — so the team moves through it, not to suppress or escape it.',
    'In performing, a team resolves differences fluidly without contesting the basic rules of decision making. Here the opposite is happening: those rules are being negotiated for the first time.',
    'Reconstituting the team during storming resets the clock, since the new group will pass through forming and storming again. Mistaking a normal developmental phase for failure is a costly and common error.',
    'In norming the norms are already agreed and accepted and the question of who decides has been settled. The scenario describes precisely the period before that.'],
 ref:'2026 ECO People · build a team; Tuckman model'},

{id:'en-p15', domain:'people', topic:'Shared vision',
 q:'Halfway through a two-year programme the team is meeting its sprint commitments, but several members say they no longer understand why the work matters, and attrition has risen. What is the most effective response?',
 o:['Increase financial incentives to reduce attrition',
    'Reconnect the work to its purpose: revisit the intended business outcome with the team and show the real impact of what has been delivered on users',
    'Tighten the discipline of ceremonies to maintain delivery pace',
    'Shorten the sprints so results become visible sooner'],
 a:1,
 r:['Financial incentives act as a hygiene factor: they may retain people temporarily but do not answer the question the team is actually asking, which is about meaning. Attrition driven by lost purpose is rarely fixed with money.',
    'Correct. The symptom is not capability or process — commitments are being met — but a disconnect between the work and its purpose, which is common in long programmes. Restoring shared vision and making real user impact visible addresses the cause, and aligns with the emphasis in PMBOK 8 and the 2026 ECO on delivering value rather than merely outputs.',
    'Tightening ceremonies treats a meaning problem as a discipline problem. The team already meets its pace; adding process pressure to demotivated people typically accelerates attrition.',
    'Shorter sprints speed feedback, but if nobody understands why the work matters, delivering it more often changes nothing. It is a process answer to a purpose problem.'],
 ref:'2026 ECO People · shared vision; PMBOK 8 — value principle'},

{id:'en-p16', domain:'people', topic:'Coaching',
 q:'A junior analyst brings you a well-reasoned solution privately but never raises it in team meetings, saying they are not confident enough. What best develops this person?',
 o:['Present the idea yourself in the meeting, crediting them publicly',
    'Prepare them through questions so they present it themselves, and create the space in the meeting for them to do so',
    'Ask them to send the proposal to the team in writing to avoid the exposure',
    'Wait for their confidence to grow naturally over time without intervening'],
 a:1,
 r:['Presenting on their behalf solves the immediate problem — the good idea reaches the team — but reinforces the dependency that needs breaking. Next time they will still need an intermediary, and public credit does not build the capability.',
    'Correct. Effective coaching uses questions to help the person build and structure their own argument, then creates the conditions for them to make it. That develops the capability rather than solving the single instance, so that next time no intervention is needed.',
    'A written channel avoids the discomfort but also avoids the learning. The difficulty lies in speaking to the group, and this option sidesteps it rather than working on it. It may serve as an interim step, not the goal.',
    'Confidence rarely emerges on its own once a person has been avoiding exposure for some time; the pattern tends to entrench. Inaction also means the team keeps missing good ideas.'],
 ref:'2026 ECO People · mentoring and coaching'},

/* ==========================  PROCESS (41%)  ========================== */

{id:'en-r01', domain:'process', topic:'Earned value management',
 q:'A project reports PV = 240,000, EV = 200,000, AC = 250,000 and BAC = 600,000. Which statement correctly describes performance?',
 o:['CPI = 0.80 and SPI = 0.83: the project is over budget and behind schedule',
    'CPI = 1.25 and SPI = 1.20: the project is under budget and ahead of schedule',
    'CPI = 0.80 and SPI = 1.20: the project is over budget but ahead of schedule',
    'CPI = 1.25 and SPI = 0.83: the project is under budget but behind schedule'],
 a:0,
 r:['Correct. CPI = EV/AC = 200,000/250,000 = 0.80, below 1, so more is being spent than budgeted for the work completed. SPI = EV/PV = 200,000/240,000 = 0.83, also below 1, so less work has been completed than planned. Both cost and schedule performance are unfavourable.',
    'These values invert both ratios, which would result from calculating AC/EV and PV/EV. Since EV is lower than both AC and PV, both indices must be below 1.',
    'The CPI is right but the SPI is wrong. EV (200,000) is less than PV (240,000), so less value has been earned than planned and the project is behind, not ahead.',
    'Both indices are inverted. With EV below AC the project cannot be under budget: it is spending more than planned per unit of work delivered.'],
 ref:'PMBOK 8 — Measurement domain; 2026 ECO Process · project finances'},

{id:'en-r02', domain:'process', topic:'Forecasting',
 q:'A project has BAC = 400,000 and a current CPI of 0.90. Root cause analysis shows the overrun came from a one-off currency movement that has now been hedged and will not recur. Which EAC formula applies?',
 o:['EAC = BAC / CPI, because current cost performance will continue',
    'EAC = AC + (BAC − EV), because the variance was atypical and the remaining work will perform to plan',
    'EAC = BAC, because the approved budget cannot be changed',
    'EAC = AC + BAC, adding what has been spent to the original budget'],
 a:1,
 r:['BAC/CPI is the formula for when the observed cost performance is expected to continue. The scenario explicitly states the cause was a one-off that has been hedged, so projecting it forward would overstate the forecast.',
    'Correct. When a variance is atypical and not expected to recur, the remaining work is forecast at its budgeted rate: EAC = AC + (BAC − EV). Choosing between EAC formulas depends entirely on the root cause analysis, and here the analysis says the cause is closed.',
    'EAC is a forecast of the expected final cost, not a restatement of the approved budget. Conflating them removes the entire purpose of forecasting.',
    'Adding AC to BAC double-counts the work already performed, since BAC already includes the budget for that work. The result has no meaningful interpretation.'],
 ref:'PMBOK 8 — forecasting; 2026 ECO Process · project finances'},

{id:'en-r03', domain:'process', topic:'Critical path',
 q:'A network has three paths: A = 22 days, B = 18 days, C = 20 days. Path B is delayed by 6 days. What is the effect on project duration?',
 o:['The project is delayed by 6 days, since any delay affects the finish date',
    'The project is delayed by 2 days, because path B becomes 24 days and overtakes path A',
    'There is no effect, because path B had 4 days of float',
    'The project is delayed by 4 days and path A remains critical'],
 a:1,
 r:['A delay only transfers fully to the finish date when it occurs on the critical path. Path B was not critical and had float, so part of the delay is absorbed before any impact occurs.',
    'Correct. Path B had 4 days of total float relative to the 22-day critical path A. A 6-day delay makes it 24 days, consuming the float and exceeding path A by 2 days. Path B becomes the new critical path and the project finish moves by exactly 2 days.',
    'Path B did have 4 days of float, but the delay is 6 days, which is 2 days more than the float available. The float is fully consumed and the excess pushes the finish date.',
    'A 4-day delay would exactly consume the float and leave the finish date unchanged. A 6-day delay exceeds it, and path A no longer remains critical once path B reaches 24 days.'],
 ref:'PMBOK 8 — Planning; 2026 ECO Process · schedule'},

{id:'en-r04', domain:'process', topic:'Schedule compression',
 q:'A project is four weeks behind on the critical path. There is no additional budget, but the sponsor accepts an increase in risk to recover time. Which technique fits best?',
 o:['Crashing: add resources to critical path activities',
    'Fast tracking: overlap critical path activities that were planned sequentially',
    'Resource levelling: rebalance the existing assignments',
    'Reduce quality standards to accelerate the remaining deliverables'],
 a:1,
 r:['Crashing shortens duration by adding resources, which by definition increases cost. The scenario states there is no additional budget, so this technique is not available here.',
    'Correct. Fast tracking overlaps activities that were planned in sequence, compressing the schedule without additional cost. The trade-off is a higher risk of rework and defects from starting work on incomplete predecessors — which is precisely the trade-off the sponsor has accepted.',
    'Resource levelling adjusts work to match resource availability and typically extends the schedule rather than compressing it. It is the opposite of what is needed.',
    'Lowering quality standards is not a recognised compression technique. It defers cost into defects and rework rather than removing it, and normally requires formal approval as a change to requirements.'],
 ref:'PMBOK 8 — Planning; 2026 ECO Process · schedule'},

{id:'en-r05', domain:'process', topic:'Risk response',
 q:'A risk has a 25% probability of occurring with an impact of 400,000. A mitigation costing 40,000 would reduce the probability to 5%. What does the analysis indicate?',
 o:['EMV falls from 100,000 to 20,000, an 80,000 reduction for a 40,000 cost, so the mitigation is economically justified',
    'EMV falls from 100,000 to 20,000, but since the risk still exists the mitigation adds no value',
    'EMV is 400,000 and the mitigation should be implemented because the impact exceeds its cost',
    'EMV falls from 25,000 to 5,000, so the 40,000 mitigation costs more than it saves'],
 a:0,
 r:['Correct. EMV before = 0.25 × 400,000 = 100,000. EMV after = 0.05 × 400,000 = 20,000. The reduction in expected exposure is 80,000 for a cost of 40,000, giving a clearly positive net benefit. Mitigation reduces probability or impact without eliminating the risk entirely.',
    'The arithmetic is right but the conclusion does not follow. Mitigation is not expected to eliminate risk; reducing expected exposure by 80,000 for 40,000 is exactly what a successful mitigation looks like.',
    'This confuses EMV with gross impact. EMV weights impact by probability, which is what makes risks comparable, and comparing raw impact to mitigation cost would justify almost any spend.',
    'These figures use 400,000 × 0.0625 or similar miscalculation. The correct products are 100,000 and 20,000, and the resulting saving comfortably exceeds the mitigation cost.'],
 ref:'PMBOK 8 — Uncertainty domain; 2026 ECO Business Environment · risk'},

{id:'en-r06', domain:'process', topic:'Contract types',
 q:'You must contract work whose scope cannot be precisely defined, and the organisation wants the seller to have a financial incentive to control costs. Which contract type is most appropriate?',
 o:['Firm Fixed Price (FFP)',
    'Cost Plus Incentive Fee (CPIF)',
    'Cost Plus Fixed Fee (CPFF)',
    'Time and Materials with no not-to-exceed ceiling'],
 a:1,
 r:['FFP requires a well-defined scope for the seller to price meaningfully. With an imprecise scope, sellers either decline, add a large risk premium, or the contract ends in dispute.',
    'Correct. CPIF satisfies both conditions in the scenario: it reimburses actual costs, which is workable when scope cannot be fixed, and it ties part of the fee to cost performance through a sharing formula, creating the incentive to control cost that the organisation wants.',
    'CPFF also reimburses costs, but the fee is fixed regardless of cost performance, so it creates no incentive to contain spending. It meets the first condition but fails the second, which is the discriminating one.',
    'T&M with no ceiling gives the buyer maximum exposure: payment by the hour with no limit and no efficiency incentive. A not-to-exceed ceiling is standard practice precisely to bound this risk.'],
 ref:'PMBOK 8 — procurement; 2026 ECO Process · procurement'},

{id:'en-r07', domain:'process', topic:'Quality',
 q:'A control chart shows all measurements within the control limits, but the last nine consecutive points fall below the centre line. The production lead argues no action is needed. What is the correct interpretation?',
 o:['The lead is right: within control limits means the process is in control',
    'A run of nine points on one side of the centre line indicates an assignable cause and should be investigated despite being within limits',
    'The control limits should be recalculated to reflect the new process behaviour',
    'Production should be halted and the affected output scrapped immediately'],
 a:1,
 r:['This applies only the limits test and ignores run-pattern analysis, which is half the value of a control chart. A process can drift systematically for a long time before it produces anything outside the limits.',
    'Correct. The rule of seven holds that seven or more consecutive points on the same side of the centre line indicate non-random behaviour, that is, an assignable cause. It is an early warning that allows investigation and correction before the process actually produces non-conforming output.',
    'Recalculating limits so the pattern disappears adjusts the instrument rather than investigating what it is reporting. Limits derive from the process capability and are not widened to suppress inconvenient signals.',
    'Halting production and scrapping output is disproportionate: every measurement is within limits, so the output is conforming. The signal calls for investigation, not a drastic reaction without diagnosis.'],
 ref:'PMBOK 8 — Delivery domain, quality; 2026 ECO Process · quality'},

{id:'en-r08', domain:'process', topic:'Change control',
 q:'A stakeholder asks a developer directly for a small enhancement, and the developer implements it mid-sprint without informing anyone. You discover it during the review. What should you do?',
 o:['Accept it as delivered, since the work is already complete and the stakeholder is influential',
    'Assess the actual impact on scope, schedule, cost and risk, process it through integrated change control, and reinforce the process with both the developer and the stakeholder',
    'Revert the change immediately to restore the approved baseline',
    'Record it in the risk register and continue'],
 a:1,
 r:['Accepting it because of the requester\'s influence establishes that the process can be bypassed by anyone with sufficient standing. It guarantees recurrence, with requests that grow steadily less small.',
    'Correct. The work being done does not make it authorised. The impact must be assessed — it may not be small once dependencies and testing are considered — and processed formally, retroactively if necessary, to keep the baselines aligned with reality. The root cause is addressed by talking to both parties.',
    'Reverting automatically before assessing is as hasty as accepting without analysis. If the enhancement delivers real value at acceptable impact, the sensible outcome is formal approval rather than destroying completed work on principle.',
    'This is a completed fact, not an uncertain future event, so the risk register is the wrong artefact. Continuing without action also leaves the baselines misaligned with what has actually been built.'],
 ref:'PMBOK 8 — change control; 2026 ECO Business Environment · governance'},

{id:'en-r09', domain:'process', topic:'Agile metrics',
 q:'A team\'s velocity has been stable at 28 points per sprint, but average cycle time has risen from 3 to 9 days and work in progress has grown. What is most likely happening?',
 o:['The team is improving, since it sustains velocity on larger items',
    'Too much work in progress: the team starts more than it finishes, which lengthens cycle time without increasing delivery',
    'Velocity is the only meaningful metric and, being stable, indicates no problem',
    'The team should commit to more points per sprint to reduce cycle time'],
 a:1,
 r:['Nothing suggests larger items, and a cycle time that triples alongside growing WIP is a flow dysfunction rather than an improvement. Stable velocity is masking the problem here, not disproving it.',
    'Correct. This is the classic signature of excessive work in progress, formalised by Little\'s Law: with a constant completion rate, more items in progress necessarily means longer cycle time. The team is starting faster than it finishes, incurring context switching and delayed feedback. The remedy is to limit WIP and finish before starting.',
    'Relying on velocity alone is exactly what conceals this problem. Flow metrics such as cycle time and WIP reveal dysfunctions that velocity by construction cannot show.',
    'Committing to more work would worsen the situation: more items started in parallel lengthens cycle time further. The correct direction is to reduce concurrent work.'],
 ref:'PMBOK 8 — Measurement domain; 2026 ECO Process · delivery and metrics'},

{id:'en-r10', domain:'process', topic:'Reserves',
 q:'Unforeseen work arises that was never identified as a risk but is required to meet the project objective. Which funding source applies and what does its use require?',
 o:['Contingency reserve, which the project manager can apply directly as it sits within the cost baseline',
    'Management reserve, which sits outside the cost baseline and normally requires sponsor or governance approval',
    'Contingency reserve, but requiring change control board approval',
    'The cost baseline, by reallocating budget from work packages not yet started'],
 a:1,
 r:['Contingency reserve covers identified risks, the known-unknowns, and does sit within the cost baseline. The scenario states explicitly that this work was never identified as a risk, so contingency is not the applicable source.',
    'Correct. Unforeseen work that was not identified in advance but falls within project scope is an unknown-unknown, funded from management reserve. Because management reserve sits outside the cost baseline and forms part of the total project budget, its use normally requires approval at the appropriate governance level.',
    'This identifies the wrong fund. It also misstates the process: using contingency for an identified risk does not require a change control board, since it is budgeted for exactly that purpose.',
    'Reallocating from unstarted work packages does not create budget; it simply underfunds those activities later. It also alters the baseline without authorisation.'],
 ref:'PMBOK 8 — budget and reserves; 2026 ECO Process · budget'},

{id:'en-r11', domain:'process', topic:'Requirements',
 q:'Near project close, a client insists that three features were requested during initiation. You can find no record of the requests or of any decision to exclude them. Which tool would have prevented this dispute?',
 o:['The risk register, documenting the possibility of client disagreement',
    'The requirements traceability matrix, linking each requirement to its source, rationale, status and the deliverables that satisfy it',
    'The project charter, which defines high level scope',
    'The lessons learned register, maintained throughout the project'],
 a:1,
 r:['The risk register could have flagged the possibility of a dispute, but it would not supply the documentary evidence of what was requested, approved and excluded, which is exactly what is missing.',
    'Correct. The requirements traceability matrix links every requirement to its origin, the business need behind it, its current status, and the deliverables or tests that satisfy it. It provides the objective record needed to demonstrate what entered scope and what was excluded, which resolves disputes of this kind.',
    'The charter authorises the project and sets high-level scope, but it does not descend to individual requirements or track their status over time.',
    'Lessons learned capture knowledge for future projects rather than traceability for the current one. They might prevent recurrence but do not resolve the present claim.'],
 ref:'PMBOK 8 — requirements; 2026 ECO Process · scope'},

{id:'en-r12', domain:'process', topic:'Definition of done',
 q:'At sprint review the product owner rejects a story for lacking automated tests. The developer notes that the story\'s acceptance criteria did not mention tests. What is the root cause?',
 o:['The product owner changed the requirements during the sprint',
    'The team\'s definition of done is absent or not shared: it is what sets the cross-cutting standards applying to every increment',
    'The developer should have inferred the testing requirement without it being written',
    'Acceptance criteria should restate all of the team\'s quality standards on every story'],
 a:1,
 r:['There is no indication of a changed requirement. Automated testing is a cross-cutting standard the product owner assumed, not a new condition introduced for this story.',
    'Correct. Acceptance criteria are story-specific and define what that functionality must do. The definition of done is the cross-cutting quality standard applying to every increment, covering things like testing, code review and documentation. Both parties believing they are right is the precise symptom of a missing or unshared definition of done.',
    'Requiring the team to infer unwritten standards guarantees recurring disputes and pushes responsibility for a team process gap onto an individual.',
    'Restating every standard on every story is redundant, unmanageable and prone to omission. The definition of done exists to state once what always applies.'],
 ref:'PMBOK 8 — adaptive approaches; 2026 ECO Process · quality'},

{id:'en-r13', domain:'process', topic:'Dependencies',
 q:'Testing cannot begin until the payment module is built, because there is nothing to test before that. Separately, management has decided not to begin the marketing campaign until testing passes. How are these dependencies classified?',
 o:['Both are mandatory dependencies inherent in the nature of the work',
    'The first is mandatory (hard logic); the second is discretionary (soft logic, an organisational choice)',
    'Both are discretionary, since they could overlap if more risk were accepted',
    'The first is external and the second is mandatory'],
 a:1,
 r:['Only the first is mandatory. Waiting for test results before marketing is a prudent organisational choice, not a physical or technical impossibility — it could be launched earlier by accepting reputational risk.',
    'Correct. A mandatory dependency is imposed by the nature of the work or by contractual or legal requirement: you cannot test what does not yet exist. A discretionary dependency reflects an organisational preference or best practice, and it is exactly the type that can be revisited when fast tracking.',
    'The first is not discretionary. It is a technical impossibility rather than a preference, and treating mandatory dependencies as negotiable during compression is a common and costly error.',
    'An external dependency involves a party outside the project team, such as a regulator or supplier. Neither of these does; both are internal to the project and the organisation.'],
 ref:'PMBOK 8 — sequencing activities; 2026 ECO Process · schedule'},

{id:'en-r14', domain:'process', topic:'Issues versus risks',
 q:'A project manager\'s risk register contains the entry: "The vendor has not delivered the authentication module, which was due last week." What error has been made?',
 o:['None: any threat to the project belongs in the risk register',
    'This is an issue, not a risk: it has already occurred and belongs in the issue log with an owner and a target resolution date',
    'It should be deleted, since vendor delivery is the vendor\'s responsibility',
    'It should be converted into a change request, since it affects the schedule'],
 a:1,
 r:['The distinction is not academic. Risks are monitored and given preventive responses; issues are actively worked to resolution with an owner and a date. Mixing them buries current problems among future possibilities.',
    'Correct. A risk is an uncertain future event; an issue is a problem already occurring. The non-delivery has materialised, so it belongs in the issue log with an owner, actions and a target date. "The vendor might miss the date" was a risk — until it happened.',
    'The cause lying with the vendor does not remove the impact on the project or the project manager\'s responsibility to manage it. Deleting it loses visibility of an active problem.',
    'A change request may eventually be needed if a baseline must change, but it does not replace logging and working the issue, which is the immediate step.'],
 ref:'PMBOK 8 — Project Work domain; 2026 ECO Process · monitoring'},

{id:'en-r15', domain:'process', topic:'Estimation',
 q:'An activity is estimated at 8 days optimistic, 12 days most likely and 34 days pessimistic. What is the PERT beta expected duration, and what does it tell you?',
 o:['18 days, equal to the simple average, indicating a symmetric distribution',
    '15 days, against a simple average of 18, indicating a distribution skewed towards the pessimistic tail',
    '18 days, since PERT is the arithmetic mean of the three estimates',
    '12 days, since PERT always returns the most likely value'],
 a:1,
 r:['The simple average is (8+12+34)/3 = 18, but the PERT beta value is 15, so they do not coincide. Concluding the distribution is symmetric contradicts a pessimistic estimate nearly three times the most likely one.',
    'Correct. PERT beta = (O + 4M + P)/6 = (8 + 48 + 34)/6 = 90/6 = 15 days, against a simple average of 18. The gap reveals a long pessimistic tail. Weighting the most likely value by four prevents an extreme worst case from dominating the estimate, though the wide range is itself a signal of high uncertainty worth investigating.',
    'PERT beta is not the arithmetic mean: it weights the most likely value by four and divides by six. The plain average corresponds to a triangular distribution.',
    'PERT does not simply return the most likely value; it weights it alongside the optimistic and pessimistic estimates. Otherwise it would add nothing to a single-point estimate.'],
 ref:'PMBOK 8 — estimating; 2026 ECO Process · schedule'},

{id:'en-r16', domain:'process', topic:'Closing',
 q:'The final deliverable has been formally accepted and the product is live. Which activity does NOT belong to project closure?',
 o:['Releasing project resources and archiving project documentation',
    'Measuring realisation of the business benefits over the following twelve months',
    'Obtaining final formal acceptance and closing open procurements',
    'Capturing final lessons learned into organisational process assets'],
 a:1,
 r:['Releasing resources and archiving documentation are core administrative closure activities.',
    'Correct. This is the exception. Benefits realisation over the following year occurs after the project closes, and responsibility for tracking it passes to the business owner or sponsor under the benefits management plan. The project delivers the capability; the benefit materialises and is measured later.',
    'Obtaining final acceptance and closing procurements are standard closure activities.',
    'Capturing final lessons learned into organisational process assets is a standard part of closure.'],
 ref:'PMBOK 8 — Closing focus area; 2026 ECO Process · closure'},

{id:'en-r17', domain:'process', topic:'Tailoring',
 q:'A project replaces a hospital records system. The clinical data rules are fixed by regulation and fully known, while the clinician-facing interface is loosely defined and users change their minds frequently. Which development approach fits best?',
 o:['Predictive throughout, given the regulatory component',
    'Hybrid: predictive for the regulated data layer, iterative for the interface',
    'Agile throughout, to maximise responsiveness',
    'Predictive, with a post-delivery phase to adjust the interface'],
 a:1,
 r:['Applying predictive throughout forces early fixing of interface requirements that the scenario describes as loose and volatile, which produces a continuous stream of formal change requests on the least stable part of the system.',
    'Correct. Tailoring matches the approach to the characteristics of each component. This project has two distinct natures: a regulated, stable core verifiable against an external standard, and an uncertain user experience layer that benefits from iteration and feedback. That is precisely the tailoring logic of PMBOK 8.',
    'Agile throughout is problematic for the regulated data layer, where requirements are neither emergent nor negotiable and formal traceability is typically required for audit. Iterating over what law already fixes adds no value.',
    'Deferring interface adjustment until after full delivery concentrates discovery at the point where change is most expensive, which is the classic driver of late-stage cost overruns.'],
 ref:'PMBOK 8 — tailoring; 2026 ECO Process · planning and delivery'},

{id:'en-r18', domain:'process', topic:'Configuration management',
 q:'Two teams have deployed different versions of the same service to different environments, and nobody is certain which version is running in production. Which discipline has been applied poorly?',
 o:['Integrated change control, which decides on change requests to the baselines',
    'Configuration management, which identifies and controls the characteristics and versions of project products and documents',
    'Quality assurance, which audits process compliance',
    'Scope management, which defines what work is included'],
 a:1,
 r:['Integrated change control governs whether changes are approved. The failure here is not improper approval but not knowing which version is deployed where, which is a different control.',
    'Correct. Configuration management identifies configuration items, controls their versions, records their status and verifies their integrity. Not knowing what is running in production is exactly the failure this discipline prevents, working alongside but distinct from change control.',
    'Quality assurance might detect the deficiency through audit, but it is the detection mechanism rather than the control whose absence caused the problem.',
    'Scope management defines what work is included, not how resulting products are versioned and controlled. Scope could be perfectly defined and this problem would persist unchanged.'],
 ref:'PMBOK 8 — configuration management; 2026 ECO Process · control'},

/* ================  BUSINESS ENVIRONMENT (26%)  ================ */

{id:'en-b01', domain:'business', topic:'2026 ECO changes',
 q:'A colleague offers you their PMP study materials, prepared in 2023. What is the most significant limitation of those materials for someone sitting the exam today?',
 o:['They are invalid because exam questions are rewritten every year',
    'Domain weighting has changed substantially — Business Environment moved from 8% to 26% — and AI, sustainability and governance content has been added that those materials do not cover',
    'They are unusable because the exam no longer includes situational questions',
    'They remain fully valid, since project management fundamentals do not change'],
 a:1,
 r:['Specific questions always change, but that alone would not invalidate good material. The issue is the content and its weighting, not the rotation of individual items.',
    'Correct. The ECO effective from 9 July 2026 reweights the domains to People 33%, Process 41% and Business Environment 26%, consolidates the task list from 35 to 26, and explicitly adds artificial intelligence, sustainability and a heavier emphasis on governance, compliance and value. Studying from pre-2026 material leaves the fastest-growing domain badly under-covered.',
    'The exam remains predominantly situational; scenario-based judgement has in fact been reinforced, alongside new interactive question formats.',
    'Fundamentals endure, but the exam tests the current ECO with specific weightings. Material devoting 8% to a domain now worth 26% leaves a substantial gap.'],
 ref:'PMI — PMP Exam Content Outline 2026'},

{id:'en-b02', domain:'business', topic:'Compliance',
 q:'Mid-project, new sector regulation takes effect that affects how your product handles personal data. Compliance requires redesigning a module and would delay delivery by five weeks. What should the project manager do?',
 o:['Deliver on schedule and plan the regulatory adaptation as a follow-on project',
    'Assess the impact, inform the sponsor and compliance function, and process the change needed to achieve conformance even though it affects the schedule',
    'Ask the client whether they prefer compliance or the original delivery date',
    'Proceed as planned, since the regulation took effect after the baseline was approved'],
 a:1,
 r:['Knowingly delivering a non-compliant product exposes the organisation to penalties, legal liability and reputational damage. Regulatory compliance is not a negotiable scope item that can be deferred for schedule convenience.',
    'Correct. For a newly applicable legal requirement, the professional sequence is to assess the real impact, inform the sponsor and the compliance function immediately since they must evaluate legal exposure, and process the change formally. Schedule is subordinated to compliance, not the reverse.',
    'Compliance with binding regulation is not a client preference. Framing it as a choice improperly transfers a decision that is not theirs to make and does not relieve the organisation of liability.',
    'The baseline approval date does not exempt the deliverable from regulation in force at delivery. Monitoring and responding to external change is an explicit project manager responsibility.'],
 ref:'2026 ECO Business Environment · compliance'},

{id:'en-b03', domain:'business', topic:'Benefits realisation',
 q:'A self-service portal is delivered on time and works correctly, with the goal of cutting support calls by 30%. Six months later calls have fallen only 5%. What does this indicate?',
 o:['The project failed, since it did not achieve its stated objective',
    'The project delivered its output successfully, but benefit realisation depends on adoption and organisational change management, which the benefits management plan should address',
    'The measurement is irrelevant, since business outcomes are no longer the project\'s concern after closure',
    'The 30% target was wrong and should be restated retrospectively'],
 a:1,
 r:['This conflates output with benefit. The project delivered what was committed, on time and functioning; what has not occurred is user adoption, which is a separate and later condition.',
    'Correct. A project delivers a capability; the benefit materialises when that capability is adopted and used. A gap of this size typically points to insufficient communication, training or adoption incentives — that is, organisational change management. The benefits management plan should name who sustains and measures the benefit after closure and trigger corrective action.',
    'The 2026 ECO reinforces the opposite: project management is oriented to value, and post-closure benefits tracking is an explicit part of the framework, even though ownership passes to the business.',
    'Restating the target retrospectively to match the outcome eliminates the opportunity to learn and correct. Targets can be revised on evidence, but not to disguise an adoption gap.'],
 ref:'2026 ECO Business Environment · value and benefits; PMBOK 8'},

{id:'en-b04', domain:'business', topic:'Artificial intelligence',
 q:'Your team proposes using a generative AI service to summarise requirements documents, uploading internal project material to it. What must the project manager address before approving?',
 o:['The licence cost against the estimated hours saved',
    'Compliance with organisational policy on confidentiality, data handling and AI use, plus who is accountable for verifying the accuracy of outputs',
    'Whether the tool is the most technically advanced option available',
    'Prohibit it, since AI is outside the scope of project management'],
 a:1,
 r:['Cost-benefit analysis is relevant but secondary. If the usage breaches confidentiality policy or data regulation, the hours saved are irrelevant next to the legal and reputational exposure created.',
    'Correct. The 2026 ECO and PMBOK 8 explicitly incorporate AI into project management, and the central concern is governing its use: what information may be uploaded under organisational policy and data regulation, and who verifies outputs that can contain plausible errors. Accountability for content remains human.',
    'Selecting the most advanced tool addresses none of the critical questions. A leading tool that is poorly governed creates exactly the same confidentiality and accuracy risks.',
    'Prohibition on principle contradicts the current framework, which treats AI as a capability to be governed rather than banned. Blanket bans also tend to drive unsupervised shadow usage.'],
 ref:'2026 ECO Business Environment · AI and governance; PMBOK 8'},

{id:'en-b05', domain:'business', topic:'Sustainability',
 q:'The sponsor asks you to account for the environmental footprint of the project and its effect on local communities, beyond financial return. How should this be integrated?',
 o:['As a communications exercise at project closure',
    'By treating sustainability criteria as requirements and decision criteria from planning onwards, with their own tracking measures',
    'By delegating it entirely to the corporate sustainability function',
    'By setting it aside, since project success is measured by scope, schedule and cost'],
 a:1,
 r:['Handling it as closing communications makes cosmetic what should shape design decisions. By the end of the project the choices with the greatest environmental impact are already made and expensive to reverse.',
    'Correct. Sustainability and ESG considerations are explicit content in the 2026 ECO and are integrated like any other requirement: identified with stakeholders, translated into design and decision criteria from planning, and tracked with defined measures. Acting early is also the cheapest point to act.',
    'The sustainability function provides expertise, but decisions on design, materials, suppliers and deployment are made inside the project. Full delegation ensures those criteria never influence anything.',
    'The triple constraint is a superseded view of success. The current framework measures success by value delivered and its wider sustainability, including effects on the environment and communities.'],
 ref:'2026 ECO Business Environment · sustainability; PMBOK 8 — stewardship'},

{id:'en-b06', domain:'business', topic:'Governance',
 q:'You need approval for a 40,000 cost overrun. The authority matrix allows you up to 15,000, the project board up to 75,000, and the executive board above that. The project board meets in four weeks and the spend is urgent. What should you do?',
 o:['Approve the 40,000 and regularise it at the next project board meeting',
    'Request an extraordinary session or use the urgent approval mechanism defined in the governance framework, documenting the impact of delay',
    'Split the spend into three amounts below your authority limit',
    'Escalate directly to the executive board to save time'],
 a:1,
 r:['Approving beyond your delegated authority and regularising afterwards is an overreach regardless of urgency. It empties the authority matrix of meaning and exposes you personally.',
    'Correct. Urgency does not change who holds authority, but governance frameworks normally provide extraordinary or urgent approval routes for exactly this situation. The correct action is to invoke them, documenting clearly the impact of not deciding so the competent body can decide with full information.',
    'Deliberately splitting a spend to stay under an authority threshold is circumvention of controls and, in many organisations, a serious disciplinary matter. The intent to evade the limit is what makes it improper.',
    'Bypassing the competent body because it is faster disrupts governance and usually ends with the executive board referring the matter back down, losing more time than it saved.'],
 ref:'2026 ECO Business Environment · governance'},

{id:'en-b07', domain:'business', topic:'Ethics',
 q:'Your sponsor asks you to present a green status to the steering committee when your analysis shows a two-month slip that has already occurred. He argues it will be recovered and that reporting now would cause unnecessary alarm. What should you do?',
 o:['Present green status, since the sponsor is the project\'s ultimate authority',
    'Report the actual status transparently, including the sponsor\'s recovery plan as part of the analysis',
    'Refuse to present and escalate immediately to the audit committee',
    'Present amber as a compromise between the two positions'],
 a:1,
 r:['A sponsor\'s authority does not extend to directing misrepresentation to a governance body. The PMI Code of Ethics requires truthful reporting, and you are accountable for what you present.',
    'Correct. The obligation is to report truthfully: the slip has already occurred, and concealing it deprives the governance body of information it needs to decide. The professional way to do this is not confrontational — present the real status and include the sponsor\'s recovery plan, incorporating his position without falsifying the data.',
    'Going straight to the audit committee is disproportionate as a first step, since the reasonable route of reporting truthfully while including the sponsor\'s view has not been attempted. Escalation is for when truthful reporting is actively prevented.',
    'Amber as a negotiated compromise is still misrepresentation, merely a subtler one. The status must reflect reality, not the midpoint of an internal negotiation.'],
 ref:'PMI Code of Ethics and Professional Conduct — honesty'},

{id:'en-b08', domain:'business', topic:'External environment',
 q:'During an 18-month project, a competitor launches a product that undermines a substantial part of your project\'s value proposition. The team continues executing the approved plan. What is the project manager\'s responsibility?',
 o:['Continue with the approved plan until the sponsor directs otherwise',
    'Analyse the impact on the business case and raise it to the sponsor and governance to decide whether to reshape, redirect or cancel',
    'Redirect the project scope independently to respond to the competitor',
    'Log it as a materialised risk and continue without further analysis'],
 a:1,
 r:['Waiting for direction when a change may have invalidated the business case is passivity rather than prudence. The project manager is usually best placed to detect such signals and is expected to raise them with analysis.',
    'Correct. The 2026 ECO strengthens continuous monitoring of the external environment. When external change affects the business case, the responsibility is to assess the impact and escalate it to those with authority to decide. Cancelling a project whose justification has disappeared is a legitimate value decision, not a project manager\'s failure.',
    'Redirecting scope independently exceeds the role\'s authority: changing the value proposition is a business decision for the sponsor and governance.',
    'Logging and continuing without assessing impact reduces the register to a passive archive. What matters is not recording the event but evaluating whether the project still makes sense.'],
 ref:'2026 ECO Business Environment · external environment'},

{id:'en-b09', domain:'business', topic:'Organisational change management',
 q:'A new system is deployed with no technical defects, yet two months later 70% of users continue using the previous manual process. What is the most likely cause and appropriate response?',
 o:['Users lack technical skill; repeat the tool training',
    'Change management has been insufficient; diagnose where adoption is breaking down — awareness, desire, knowledge, ability or reinforcement — and act on that specific point',
    'Withdraw access to the manual process to force migration',
    'The system has hidden defects and requires another test cycle'],
 a:1,
 r:['Repeating training is the reflex response and works only if the blockage genuinely lies in knowledge or ability. If users do not understand why they should change or do not want to, more training changes nothing.',
    'Correct. Thirty percent adoption after a technically clean deployment is an organisational change problem, not a technology problem. Frameworks such as ADKAR let you diagnose which specific link is breaking — awareness, desire, knowledge, ability or reinforcement — and apply the matching intervention rather than guessing.',
    'Forcing migration by closing the old process may raise nominal adoption, but without diagnosing the cause it generates resistance, errors and informal workarounds. It is sometimes used, but never before understanding why.',
    'Nothing suggests defects; the deployment was clean. Hunting for a technical fault where the problem is behavioural wastes time and reinforces the mistaken belief that technology will drive adoption.'],
 ref:'2026 ECO Business Environment · organisational change'},

{id:'en-b10', domain:'business', topic:'Project selection',
 q:'Two candidate projects require similar investment. Project A has an NPV of 500,000 with a five-year payback; Project B has an NPV of 300,000 with a fourteen-month payback. The organisation is under short-term cash pressure. What is the most complete analysis?',
 o:['Choose A, because NPV is the financially superior measure',
    'A creates more absolute value, but under liquidity constraints B\'s payback period may be decisive; the decision should weigh both measures against the context',
    'Choose B, because faster payback eliminates risk',
    'They are equivalent, since the initial investment is similar'],
 a:1,
 r:['NPV is the strongest measure of value creation because it accounts for the time value of money, but applying it mechanically ignores real constraints. An organisation short of cash may never realise that superior value.',
    'Correct. A\'s NPV indicates greater absolute value creation, while payback period measures something different and here critical: how quickly cash is freed. Under liquidity pressure that dimension can be decisive. Selection measures are complementary and must be weighed alongside strategic and risk context.',
    'Faster payback reduces temporal exposure but does not eliminate risk, and choosing B forgoes 200,000 of value. Absolute rules discard the context that makes the analysis useful.',
    'Similar initial investment is what makes the two comparable, not what makes them equivalent. They differ in value created and in cash timing, which are the two decision-relevant dimensions.'],
 ref:'2026 ECO Business Environment · business case'},

{id:'en-b11', domain:'business', topic:'Strategic alignment',
 q:'You realise your project, approved a year ago, no longer fits the strategic priorities the executive team announced last month. The project is on schedule and on budget. What should you do?',
 o:['Continue, since the project is meeting its schedule and cost objectives',
    'Formally raise the alignment question with the sponsor and portfolio governance, supported by an updated value analysis',
    'Adjust the scope yourself to align with the new strategy',
    'Accelerate delivery to finish before the project is questioned'],
 a:1,
 r:['Meeting schedule and cost is meaningless if the project no longer delivers strategic value. It amounts to executing efficiently something the organisation no longer needs.',
    'Correct. Strategic alignment is a shared responsibility, and the project manager typically has the visibility to spot the misalignment first. Raising it formally with an updated value analysis lets portfolio governance decide whether to continue, redirect or cancel.',
    'Changing scope unilaterally to chase the new strategy exceeds the role\'s authority, bypasses change control and is likely to produce imagined rather than real alignment.',
    'Rushing to complete before scrutiny puts the interest of finishing above the interest of the organisation. It contravenes the PMI Code of Ethics and deliberately destroys value.'],
 ref:'2026 ECO Business Environment · strategic alignment'},

{id:'en-b12', domain:'business', topic:'Continuous improvement',
 q:'Across several retrospectives the team keeps identifying the same process problem, but it is never fixed because there is "no time". What is the most effective intervention?',
 o:['Hold retrospectives less often, since they are not producing change',
    'Treat improvement actions as prioritised work items with explicitly allocated capacity in the iteration and a named owner',
    'Delegate process improvement to the PMO so it does not consume team time',
    'Accept that the problem is structural and record it as a project constraint'],
 a:1,
 r:['Reducing retrospectives removes the detection mechanism instead of fixing the execution one. The diagnosis is working correctly; what fails is that nothing becomes action.',
    'Correct. When improvement actions compete informally against delivery work, they always lose. Treating them as real work — added to the backlog with priority, given explicit capacity in the iteration and assigned an owner — is what stops continuous improvement depending on leftover time.',
    'The PMO can support and provide method, but a team process problem is not solved from outside without the team\'s involvement. Delegating without allocating time reproduces the same blockage.',
    'Labelling it a structural constraint is surrender on a problem the team has repeatedly shown it can identify. Continuous improvement is an explicit principle, not a luxury contingent on spare time.'],
 ref:'2026 ECO Business Environment · continuous improvement'}

];
if (typeof window !== 'undefined') window.QUESTIONS_EN = QUESTIONS_EN;
